# Halloween Barrel Configuration
# This file contains all configuration settings for the Halloween barrel project

# Distance thresholds for triggering different behaviors
distance_thresholds:
  warning: 100.0    # cm - object approaching warning
  trigger: 50.0     # cm - execute Halloween sequence    # seconds - time between distance readings

# Hardware pin configuration (BCM numbering)
hardware:
  motor_pins:
    forward: 6
    reverse: 5
  pump_relay_pin: 21
  smoke_relay_pin: 20
  ultrasonic_pins:
    trigger: 8
    echo: 7
  ultrasonic_2_pins:
  govee_light:            # Set to true to enable Govee light
    ip_address: "192.168.1.212"  # IP address of Govee light                # UDP port for Govee communication              # Volume level (0.0 to 1.0)

# Logging configuration
logging:
  level: "INFO"                  # Logging level: DEBUG, INFO, WARNING, ERROR
  file: "halloween_barrel.log"   # Log file path
  console: true                  # Enable console logging
